"""Keyboard builders package — re-exports for backward compatibility."""

from .common import PAGE_SIZE, build_feature_config_menu
from .user import (
    build_main_menu,
    build_tags_menu,
    build_community_tags_menu,
    build_prompts_by_tag_menu,
    build_prompt_preview_menu,
    build_my_prompts_menu,
    build_user_prompt_card,
)
from .admin import (
    build_admin_menu,
    build_admin_tags_menu,
    build_admin_tag_item_menu,
    build_prompt_work_menu,
    build_prompt_list_menu,
    build_admin_prompt_tags_menu,
    build_admin_users_with_prompts_menu,
    build_admin_user_prompts_menu,
    build_prompt_item_menu,
    build_prompt_edit_menu,
    build_prompt_edit_tags_menu,
    build_prompt_edit_variables_menu,
    build_prompt_edit_variable_actions_menu,
    build_promo_menu,
    build_promo_list_menu,
    build_promo_item_menu,
    build_admin_prompt_card,
    build_admin_community_card,
)

__all__ = [
    "PAGE_SIZE",
    "build_feature_config_menu",
    "build_main_menu",
    "build_tags_menu",
    "build_community_tags_menu",
    "build_prompts_by_tag_menu",
    "build_prompt_preview_menu",
    "build_my_prompts_menu",
    "build_user_prompt_card",
    "build_admin_menu",
    "build_admin_tags_menu",
    "build_admin_tag_item_menu",
    "build_prompt_work_menu",
    "build_prompt_list_menu",
    "build_admin_prompt_tags_menu",
    "build_admin_users_with_prompts_menu",
    "build_admin_user_prompts_menu",
    "build_prompt_item_menu",
    "build_prompt_edit_menu",
    "build_prompt_edit_tags_menu",
    "build_prompt_edit_variables_menu",
    "build_prompt_edit_variable_actions_menu",
    "build_promo_menu",
    "build_promo_list_menu",
    "build_promo_item_menu",
    "build_admin_prompt_card",
    "build_admin_community_card",
]
